product_color:
    code:
        no_color: 0
        red: 1
        blue: 2
        green: 3
        white: 4
        black: 5
    name:
        no_color: No-Color
        red: Red
        blue: Blue
        green: Green
        white: White
        black: Black

product_come_from:
    code:
        inside: 0
        outside: 1
    name:
        inside: "Nội nhập"
        outside: "Ngoại nhập"
        
have_vat:
    code:
        not_have: 0
        have: 1
    name:
        not_have: NOT VAT
        have: VAT
